---------------------------------------------------------------------------------------------------
--                                     Spider Solitaire                                           |
-- Created by Nicacio, Damiao, Daniela, Lucas and Kelvin on 05/20/18 for the discipline of PLP.   |
-- UFCG - Campina Grande - PB                                                                     |
---------------------------------------------------------------------------------------------------
